config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index'

  resources :doctors
  resources :patients
  resources :appointments, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  def information
    "Appointment on #{date}, #{time}, at #{location}"
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates_presence_of :name, :specialty, :hospital

  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates_presence_of :first_name, :last_name, :age, :gender
  validates_inclusion_of :gender, in: ['Male', 'Female', 'Other']

  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def new
    @doctors = Doctor.all.map { |d| [d.name, d.id] }
    @patients = Patient.all.map { |p| [p.full_name, p.id]}
    @appointment = Appointment.new
  end

  def show
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to :back, notice: 'Appointment was Created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to :back, notice: 'Appointment was Updated'
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to :back, notice: 'Appointment was Deleted'
  end

  private
    def set_appointment 
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:doctor_id, :patient_id, :date, :time, :location)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor, notice: 'Doctor was Created'
    else
      render :new
    end
  end 

  def edit
  end

  def update 
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'Doctor was Updated'
    else
      render :edit
    end
  end

  def destroy 
    @doctor.destroy
    redirect_to :root, notice: 'Doctor was Deleted'
  end

  private
    def set_doctor 
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params 
      params.require(:doctor).permit(:name, :specialty, :hospital)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def show 
    @appointments = @patient.appointments
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path, notice: 'Patient was Created'
    else
      render :new
    end
  end

  def edit
  end

  def update 
    if @patient.update(patient_params)
      redirect_to patients_path, notice: 'Patient was Updated'
    else
      render :edit
    end
  end

  def destroy 
    @patient.destroy
    redirect_to patients_path, notice: 'Patient was Deleted'
  end

  private
    def set_patient 
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :age, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>
 <%= f.select :doctor_id, options_for_select(@doctors) %>
 <%= f.select :patient_id, options_for_select(@patients) %>
 <%= f.date_field :date, required: true, placeholder: 'Date' %>
 <%= f.time_field :time, required: true, placeholder: 'Time' %>
 <%= f.text_field :location, required: true, placeholder: 'Hospital' %>
 
 <%= f.submit nil, class: 'btn deep-purple lighten-1 white-text' %>
<% end %>

<hr />
<%= link_to 'All Doctors', doctors_path, class: 'btn deep-purple lighten-1 white-text' %> |
<%= link_to 'All Patients', patients_path, class: 'btn deep-purple lighten-1 white-text' %> |
<%= link_to 'Back', :back, class: 'btn deep-purple lighten-1 white-text' %>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>

<%= render 'form', appointment: @appointment %>

app/views/appointments/new.html.erb
<h1>Add New Appointment</h1>

<%= render 'form', appointment: @appointment %>

app/views/doctors/_form.html.erb
<%= form_for(doctor) do |f| %>
  <% if doctor.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :specialty %>
    <%= f.text_field :specialty %>
  </div>

  <div class="field">
    <%= f.label :hospital %>
    <%= f.text_field :hospital %>
  </div>

  <div class='actions'>
    <%= f.submit 'Submit', class: 'btn deep-purple lighten-1 white-text' %> |
    <%= link_to 'Back', :back, class: 'btn deep-purple lighten-1 white-text' %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Specialty</th>
      <th>Hospital</th>
      <th colspan='4'></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.specialty %></td>
        <td><%= doctor.hospital %></td>
        <td><%= link_to 'Show', doctor, class: 'btn deep-purple lighten-1 white-text' %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor), class: 'btn deep-purple lighten-1 white-text' %></td>
        <td><%= link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn deep-purple lighten-1 white-text' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<%= link_to 'New Doctor', new_doctor_path, class: 'btn deep-purple lighten-1 white-text' %> |

<%= link_to 'Add Patient', new_patient_path, class: 'btn deep-purple lighten-1 white-text' %>

app/views/doctors/new.html.erb
<h1>Add New Doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/show.html.erb
<h1>Doctor: <%= @doctor.name %> </h1>

<% unless @doctor.specialty.empty? %>
    <p>
      <strong>Specialty:</strong>
      <%= @doctor.specialty %>
    </p>
    <hr />
<% end %>

<% unless @doctor.hospital.empty? %>
    <p>
      <strong>Hospital:</strong>
      <%= @doctor.hospital %>
    </p>
    <hr />
<% end %>

<% if @doctor.patients.any? %>
    <h5> Patients </h5>
    <ul>
        <% @doctor.appointments.each do |appointment| %>
          <li>
            <%= appointment.patient.full_name %> - <%= appointment.information %> -
            <%= link_to 'Remove', appointment_path(appointment), method: :delete, data: {confirm: 'Really remove this appointment?'}, class: 'btn deep-purple lighten-1 white-text' %>
          </li>
        <% end %>
    </ul>
<% else %>
  <h5>No Patients Found</h5>
<% end %>

<%= link_to 'All Doctors', doctors_path, class: 'btn deep-purple lighten-1 white-text' %> |
<%= link_to 'Edit', edit_doctor_path(@doctor), class: 'btn deep-purple lighten-1 white-text' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrOffice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class='indigo darken-4'>
      <div class='nav-wrapper'>
        <a href='/' class= 'brand-logo'>Doctor Appointments</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li> <%= link_to 'Doctors', doctors_path %> </li>
          <li> <%= link_to 'Patients', patients_path %> </li>
          <li> <%= link_to 'Add Appointment', new_appointment_path %> </li>
        </ul>  
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(patient) do |f| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class='field'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class='field'>
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class='field'>
    <%= f.label :gender %>
    <%= f.select :gender, ['Male', 'Female', 'Other'], {}, class: 'browser-default' %>
  </div>

  <div class='actions'>
    <%= f.submit 'Submit', class: 'btn deep-purple lighten-1 white-text' %> |
    <%= link_to 'Back', :back, class: 'btn deep-purple lighten-1 white-text' %>
  </div>

  
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.gender %></td>
        <td><%= link_to 'Show', patient_path(patient), class: 'btn deep-purple lighten-1 white-text' %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient), class: 'btn deep-purple lighten-1 white-text' %></td>
        <td><%= link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn deep-purple lighten-1 white-text' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class: 'btn deep-purple lighten-1 white-text' %>

app/views/patients/new.html.erb
<h1>Add New Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1>

<table>
  <thead>
    <tr>
      <th>Appointment Date</th>
      <th>Appointment Time</th>
      <th>Hospital</th>
      <th colspan='4'></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.time %></td>
        <td><%= appointment.location %></td>
        <td><%= link_to 'Delete', appointment_path(appointment), 
                method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn deep-purple lighten-1 white-text' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', patients_path, class: 'btn deep-purple lighten-1 white-text' %>